import json
import boto3
import os
from datetime import datetime
from io import BytesIO

# Initialize AWS clients
s3_client = boto3.client('s3')

def lambda_handler(event, context):
    """
    Generate attendance report with start time and end time columns.
    """
    
    try:
        # Parse the incoming request
        body = json.loads(event['body'])
        attendance_data = body.get('attendanceData', [])
        date = body.get('date', datetime.now().strftime('%Y-%m-%d'))
        start_time = body.get('startTime', '00:00')
        end_time = body.get('endTime', '00:00')
        bucket_name = os.environ.get('S3_BUCKET_NAME')
        
        print(f"Generating report for {len(attendance_data)} students")
        print(f"Date: {date}, Start: {start_time}, End: {end_time}")
        
        # Create CSV report
        csv_content = generate_csv_report(attendance_data, date, start_time, end_time)
        
        # Generate filename
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f"attendance_report_{timestamp}.csv"
        s3_key = f"reports/{filename}"
        
        # Upload to S3
        s3_client.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=csv_content,
            ContentType='text/csv',
            ContentDisposition=f'attachment; filename="{filename}"'
        )
        
        print(f"Report uploaded to S3: s3://{bucket_name}/{s3_key}")
        
        # Generate presigned URL for download (valid for 7 days)
        download_url = s3_client.generate_presigned_url(
            'get_object',
            Params={
                'Bucket': bucket_name,
                'Key': s3_key
            },
            ExpiresIn=604800  # 7 days
        )
        
        return {
            'statusCode': 200,
            'headers': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Content-Type',
                'Access-Control-Allow-Methods': 'POST, OPTIONS'
            },
            'body': json.dumps({
                'success': True,
                'downloadUrl': download_url,
                'filename': filename,
                's3Location': f"s3://{bucket_name}/{s3_key}",
                'totalStudents': len(attendance_data)
            })
        }
        
    except Exception as e:
        print(f"Error: {str(e)}")
        import traceback
        traceback.print_exc()
        
        return {
            'statusCode': 500,
            'headers': {
                'Access-Control-Allow-Origin': '*',
                'Access-Control-Allow-Headers': 'Content-Type',
                'Access-Control-Allow-Methods': 'POST, OPTIONS'
            },
            'body': json.dumps({
                'error': str(e),
                'message': 'Failed to generate report'
            })
        }


def generate_csv_report(attendance_data, date, start_time, end_time):
    """
    Generate CSV content with start time and end time columns.
    """
    
    # CSV Header with metadata
    csv_lines = [
        "VIT VELLORE - ATTENDANCE REPORT",
        f"Date: {date}",
        f"Start Time: {start_time}",
        f"End Time: {end_time}",
        f"Total Students: {len(attendance_data)}",
        "",
        "S.No,Name,Registration Number,Date,Start Time,End Time"
    ]
    
    # Add each student with start and end time
    for i, student in enumerate(attendance_data, start=1):
        name = student.get('name', 'Unknown')
        rg_number = student.get('rgNumber', 'N/A')
        csv_lines.append(f"{i},{name},{rg_number},{date},{start_time},{end_time}")
    
    # Add footer
    csv_lines.extend([
        "",
        f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        "Generated by VIT Attendance System"
    ])
    
    return '\n'.join(csv_lines)


# Example test event
"""
{
  "body": "{\"attendanceData\":[{\"name\":\"John Doe\",\"rgNumber\":\"21BCE1234\"},{\"name\":\"Jane Smith\",\"rgNumber\":\"21BCE5678\"}],\"date\":\"2024-11-10\",\"startTime\":\"09:00\",\"endTime\":\"10:00\"}"
}
"""
